In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(f"{a} \n{b}")

[1 2 3 4] 
[5 6 7 8]


In [3]:
c = a+b
print(c)

[ 6  8 10 12]


In [4]:
print(type(c))

<class 'numpy.ndarray'>


In [8]:
print(c.size)

4


In [7]:
print(c.shape)

(4,)


In [10]:
print(c.sum())

36


# practice sets

In [11]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [12]:
print(x.sum())

45


In [13]:
print(x.min())

1


In [14]:
print(x.mean())

5.0


In [15]:
print(x.std())

2.581988897471611


In [17]:
print(x.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
