In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [5]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
print(b.size)

6


In [7]:
print(b.nbytes)

24


In [12]:
x = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
print(x.size)

9


In [14]:
print(x[1][2])

6


In [16]:
print(x.sum())

45


In [17]:
print(x.sum(axis= 0)) # column

[12 15 18]


In [18]:
print(x.sum(axis=1)) # row

[ 6 15 24]


In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(a[0,:]) # accessing particular row

[1 2 3]


In [22]:
print(a[1,:])

[4 5 6]


In [23]:
print(a[1,:2]) # accessing row by slicing

[4 5]


In [25]:
print(a[:,2]) # accessing particular column

[3 6 9]


In [27]:
x = np.arange(15) # provies array in range of input
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
x=np.zeros(5) # inserts zero in all indexes
print(x)
x=np.ones(5) # inserts one in all indexes
print(x)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [32]:
x = np.full([2,3],9) # inserting elements in matrix of particular dimension
print(x)

[[9 9 9]
 [9 9 9]]


In [39]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
