In [4]:
import numpy as np
print(np.__version__)

1.23.5


In [13]:
a = np.array([1, 2, 3, 4, 5, 6]) # default 32 bit # a = np.array([1, 2, 3, 4, 5, 6], dtype= 'int16')
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.nbytes)
print(a.ndim)
print(a.dtype)
a

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)
6
24
1
int32


array([1, 2, 3, 4, 5, 6])

In [18]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([7, 8, 9, 10, 11,12])
print(x + y)
print(x - y)
print(x / y)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
